### PR TITLE
Update for KF6 (KDE 6)

### PR DESCRIPTION
**Pull request by xynnylol**
KDE 6 has updated how themes work, This ports it from KDE 5 to the latest KDE 6

Code might be a bit messy as this was a 20 minute job but feel free to check it out.

### CODE REVIEW

**Comment by tsujan** [comment]
Much appreciated.

I'll upgrade BreezeEnhanced after a stable version of Plasma6 comes to my distro (Manjaro Testing). Your work will be of great help.

**Comment by xynnylol** [comment]
> Much appreciated.
> 
> I'll upgrade BreezeEnhanced after a stable version of Plasma6 comes to my distro (Manjaro Testing). Your work will be of great help.

No problem, Its stable on arch already :skull: unfortunately it doesn't come with backwards compatability for old global themes and decorations

**Comment by tsujan** [comment]
I'll need to compare the new version of breeze with breeze-5.27.11 to apply only the relevant changes, without losing the changes that I've made (more changes might be needed too). Comparing the final result with your patch will be helpful.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/BreezeEnhanced/commit/b3de58529be2a671414b44f318993dbd34fd1eda

**Comment by tsujan** [comment]
Oh, I forgot to say that I used some parts of your PR. But since the config dialog of BreezeEnhanced wasn't shown with it, I had to make changes based on Breeze's code. The rest was about code cleanup (which isn't complete yet but doesn't affect functionality).

Thanks for making the job easier!

**Comment by xynnylol** [comment]
> Oh, I forgot to say that I used some parts of your PR. But since the config dialog of BreezeEnhanced wasn't shown with it, I had to make changes based on Breeze's code. The rest was about code cleanup (which isn't complete yet but doesn't affect functionality).
> 
> Thanks for making the job easier!

No problem, I use your theme and when kde6 broke it i was annoyed so i made a hot fix :laughing:

**Pull request closed without merging**
